branch-defaults:
  default:
    environment: project-nst-dev
    group_suffix: null
global:
  application_name: project_nst
  branch: null
  default_ec2_keyname: rookienokey
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
